# Test Lakehouse - DX Demo
name: dx-demo
description: Demonstrating the new Phlo DX features

# NEW FEATURE: Service customization in phlo.yaml!
services:
  # Override Observatory port
  observatory:
    ports:
      - "9000:3000"
    environment:
      NODE_ENV: development
      CUSTOM_VAR: "Hello from phlo.yaml!"

  # Disable Superset (we don't need BI for this demo)
  superset:
    enabled: false

  # Add a custom inline service!
  hello-world:
    type: inline
    image: hashicorp/http-echo
    ports:
      - "5678:5678"
    command: ["-text", "Hello from a custom inline service!"]
